# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

platform:
  - x64

environment:
  matrix:
    - ARGS: --toolset=msvc-9.0  address-model=32 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-9.0  address-model=32 
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=msvc-10.0 address-model=32 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-10.0 address-model=32 
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=msvc-11.0 address-model=32 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-11.0 address-model=32 
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=msvc-12.0 address-model=32 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-12.0 address-model=32 
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=msvc-14.0 address-model=32 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-14.0 address-model=32 
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=msvc-12.0 address-model=64 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-12.0 address-model=64 
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=msvc-14.0 address-model=64 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - ARGS: --toolset=msvc-14.0 address-model=64 
      TARGETS: conversions misc compile_fail examples concepts
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=64 cxxstd=17
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=64 cxxstd=17 
      TARGETS: conversions misc compile_fail examples concepts
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=32  cxxstd=17
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=32  cxxstd=17
      TARGETS: conversions misc compile_fail examples concepts
    - ARGS: --toolset=gcc address-model=64 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
    - ARGS: --toolset=gcc address-model=64 
      TARGETS: conversions misc compile_fail examples concepts
      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
    - ARGS: --toolset=gcc address-model=64 cxxstd=2a cxxstd-dialect=gnu 
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
    - ARGS: --toolset=gcc address-model=64 cxxstd=2a cxxstd-dialect=gnu 
      TARGETS: conversions misc compile_fail examples concepts
      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%


install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init libs/config
  - git submodule update --init libs/polygon
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\multiprecision
  - git submodule update --init tools/boostdep
  - python tools/boostdep/depinst/depinst.py multiprecision
  - bootstrap
  - b2 headers

build: off

test_script:
  - cd libs\config\test
  - ..\..\..\b2 config_info_travis_install %ARGS%
  - config_info_travis
  - cd ..\..\multiprecision\test
  - ..\..\..\b2 --hash -j3 %ARGS% %TARGETS% define=CI_SUPPRESS_KNOWN_ISSUES
